In [21]:
import numpy as np

class Solution:
    def matrixSum(self, n, operations):
        # Write Code Here
        num = 0
        mat = np.zeros((n,n))
        while num<len(operations):
            ope_here = operations[num]
            #ope_here.append(operations[num])
            #ope_here.append(operations[num+1])
            #ope_here.append(operations[num+2])
            idx = int(ope_here[1])
            val = ope_here[2]
            if ope_here[0] == 0:
                mat[idx] = val
            if ope_here[0] == 1:
                for row in mat:
                    #row = int(row)
                    row[idx] = val
            num+=1
        sum = np.sum(mat)
        return mat

n = int(input())

operations_rows, operations_cols = list(map(int, input().split()))

operations = []
for operations_i in range(operations_rows):
    operations.append(list(map(int, input().split())))


s = Solution()
res = s.matrixSum(n, operations)

print(res)


 3
 5 3
 0 0 4
 0 1 2
 1 0 1
 0 2 3
 1 2 1


[[1. 4. 1.]
 [1. 2. 1.]
 [3. 3. 1.]]


In [18]:
 3
 5 3
 0 0 4
 0 1 2
 1 0 1
 0 2 3
 1 2 1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
 3
 4 3
 0 0 1
 1 2 2
 0 2 3
 1 0 4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
mat = np.zeros((3,3))
mat[0][0]

0.0

In [30]:
bag = [0,0,1,1,2]
a = bag.sort()
del a

In [36]:
round(10/4,0)

2.0

In [45]:
n_bag = int(input())
bag = []
for i in range(n_bag):
    bag.append(int(input()))
n = 0
while sum(bag) !=0:
    min_num = bag.copy()
    while min(min_num) == 0:
        min_num.remove(0)
    min_num = min(min_num)
    
    for i,item in enumerate(bag):
        if item!=0:
            if item % min_num !=0:
                item-= round(item/min_num,0)*min_num
            else:
                item = 0
            bag[i] = item
            n+=1

print(n-1)


 5
 1
 5
 0
 3
 5


3


In [101]:
#n = int(input())
#bag = []

class Bag_solution:
    def __init__(self):
        self.n = int(input())
        self.bag = []
        self.num_to_pick = 0
        self.total_numbers = 0
        for i in range(self.n):
            self.bag.append(int(input()))
        
    def number_to_pick(self):
        temp = self.bag.copy()
        self.num_to_pick = min(temp)
        
        while self.num_to_pick == 0:
            temp.remove(0)
            self.num_to_pick = min(temp)
            print('Bag status:',self.bag,'\n')
        print('Now,number to pick = ',self.num_to_pick,'\n')
            
    def pick_from_bag(self):
        self.number_to_pick()
        print('Start picking','\n')
        for i in range(len(self.bag)):
            if self.bag[i] !=0:
                self.bag[i] = self.bag[i] - self.num_to_pick
        print('Now, bags status:',self.bag,'\n')
        self.num_to_pick = 0
            #print(self.num_to_pick)
            #print(self.bag)
            
    def pick(self):
        n = 0
        while sum(self.bag)!=0:
            n+=1
            print('Trial:',n)
            #self.number_to_pick()
            self.pick_from_bag()
            

        return n
   

In [104]:
a = [0,1,12,0,3,5]
a.

0

In [102]:
b = Bag_solution()
b.pick()

 5
 1
 5
 0
 3
 5


Trial: 1
Bag status: [1, 5, 0, 3, 5] 

Now,number to pick =  1 

Start picking 

Now, bags status: [0, 4, 0, 2, 4] 

Trial: 2
Bag status: [0, 4, 0, 2, 4] 

Bag status: [0, 4, 0, 2, 4] 

Now,number to pick =  2 

Start picking 

Now, bags status: [0, 2, 0, 0, 2] 

Trial: 3
Bag status: [0, 2, 0, 0, 2] 

Bag status: [0, 2, 0, 0, 2] 

Bag status: [0, 2, 0, 0, 2] 

Now,number to pick =  2 

Start picking 

Now, bags status: [0, 0, 0, 0, 0] 



3

In [84]:
for i, j in enumerate([1,2,3,4,5]):
    print(i,j)

0 1
1 2
2 3
3 4
4 5


In [107]:
n = int(input())
dp = {}
dp[0]= 1
dp[1] = 1
def calc_num(n):
    for i in range(2,n):
        dp[i] = dp[i-1]+dp[i-2]
    return dp[i]

calc_num(n)

 6


8

In [ ]:
st = input().split()
n,k = int(st[0]), int(st[1])

def money(st,k):
  maxLength = 0
  l,r=0,0
  count_zero = 0
   
  while r < len(st):
    if st[r] == '0':
      count_zero += 1
     
    while count_zero > k:
      if st[l] == '0':
        count_zero -= 1
      l += 1
     
    maxLength = max(maxLength, r-l+1)
    r += 1
     
  return maxLength
   

lst = input().split()
print(money(lst,k))

In [ ]:
sticks = [i+1 for i in range(int(input()))]
